import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Background from "../components/Background";

const Home: NextPage = () => {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <div className="">
        <h1 className="sm-heading text-[#52b69a]">Hi, my name is</h1>
        <h2 className="lg-heading font-bold">Matheus Fabris.</h2>
        <h3 className="lg-heading">I like building things.</h3>
      </div>
    </div>
  );
};

export default Home;
